export  const btns = [
  {linkTo: 'best_start_day', title: 'ЛУЧШЕЕ НАЧАЛО ДНЯ'},
  {linkTo: 'best_end_day', title: 'ЛУЧШЕЕ <br class="show_420">ЗАВЕРШЕНИЕ ДНЯ'},
  {linkTo: 'women_energy', title: 'ЖЕНСКАЯ <br class="show_400">ЭНЕРГИЯ'},
  {linkTo: 'women_health', title: 'ЖЕНСКОЕ <br class="show_400">ЗДОРОВЬЕ'},
  {linkTo: 'women_charisma', title: 'ЖЕНСКАЯ <br class="show_400">ХАРИЗМА'},
  {linkTo: 'women_self', title: 'ЖЕНСКАЯ <br class="show_400">САМОСТЬ'},
  {linkTo: 'women_independence', title: 'ЖЕНСКАЯ <br class="show_500">НЕЗАВИСИМОСТЬ'},
  {linkTo: 'women_dreams', title: 'ЖЕНСКИЕ МЕЧТЫ'},
  {linkTo: 'women_soul', title: 'ЖЕНСКАЯ ДУША'},
  {linkTo: 'podcast', title: 'ПОДКАСТЫ'},
  {linkTo: 'sos_programs', title: 'SOS-ПРОГРАММЫ'},
  {linkTo: 'new-menu', title: 'НОВИНКИ МЕСЯЦА'},
  {linkTo: 'hits', title: 'ХИТЫ 2023 ГОДА'},
  {linkTo: 'instructions', title: 'ИНСТРУКЦИИ'},
  {linkTo: 'support', title: 'ПОДДЕРЖКА'},
]